services:
  - type: web
    name: fusionbrain-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        scope: build,runtime
      - key: TELEGRAM_TOKEN
        scope: build,runtime
      - key: TELEGRAM_CHAT_ID
        scope: build,runtime
      - key: GMAIL_CLIENT_ID
        scope: build,runtime
      - key: GMAIL_CLIENT_SECRET
        scope: build,runtime
      - key: PORT
        value: "8000"
